name: tic_tac_go
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  get_hooked: ^0.5.1
  get_hooked_storage: ^0.1.1
  marionette_flutter: ^0.6.0
  meta: ^1.18.0
  shared_preferences: ^2.5.5
  window_manager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  get_hooked:
    path: ../get_hooked/packages/get_hooked
  get_hooked_storage:
    path: ../get_hooked/packages/get_hooked_storage

flutter:
  assets:
    - assets/

  shaders:
    - shaders/paper.frag
    - shaders/marker.frag

  fonts:
    - family: patrick hand
      fonts:
        - asset: assets/fonts/PatrickHand.ttf
    - family: permanent marker
      fonts:
        - asset: assets/fonts/PermanentMarker.ttf